build.sh: correctly use quoted $BUILD_OPTIONS
Previously we built the (centos only?) image label like this:

  "io.openshift.builder-version": "\"7ab45d0\"",

... which was wrong, but it did not hurt Docker.  Now
buildah/podman complaints:

Error: invalid argument
"io.openshift.builder-version=\"7ab45d0\"" for "--label" flag:
parse error on line 1, column 29: bare " in non-quoted-field